dubbo:
  application:
    logger: slf4j
    name: dubbo-account-example
    qos-enable: false
  registry:
    address: nacos://127.0.0.1:8848
    group: SEATA_EXAMPLE_GROUP
  protocol:
    name: tri
    port: 50051
mybatis:
  mapper-locations: classpath*:/mapper/*.xml
server:
  port: 8101
spring:
  application:
    name: dubbo-account-example
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/db_account?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    password: root
    username: root
    druid:
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: 123456

seata:
  # TC 服务注册中心的配置，微服务根据这些配置信息去注册中心获取TC服务地址
  # 参考tc服务自己的registry.conf中的配置，包括addr，namespace，group，application-name，cluster
  registry:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      namespace: ""# 默认的namespace，即public
      group: SEATA_EXAMPLE_GROUP
      application: seata-tc-server  # tc服务在nacos中注册的服务名称
  tx-service-group: seata-demo
  service:
    vgroup-mapping: # 事务组与tc服务cluster的映射关系
      seata-demo: SH
  data-source-proxy-mode: AT